spring.application.name=expense-tracker


server.port = 8081

spring.datasource.initialization-mode=always

#data source is a java obj having properties for app.prop file
#if we have jdbc dependecy but not mentioned in app.prop code ftega


#spring DB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/EXPENSE_TRACKER
spring.datasource.username=root
spring.datasource.password=Godisgood1216
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

logger.level.root=INFO

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gaurav12asap@gmail.com
spring.mail.password=sknn pmjp wfde hjwh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.ai.google.genai.api-key=AIzaSyB793pHHkjL4aIS_3a7vlbv6n1khSxUMdsh

