spring.application.name=expense-tracker


server.port = 8081

spring.datasource.initialization-mode=always

#data source is a java obj having properties for app.prop file
#if we have jdbc dependecy but not mentioned in app.prop code ftega




